spring:
 application:
   name: configserver


cloud:
  config:
    uri: https://github.com/Ramadan877/config-repo

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

