spring:
  application:
    name: registryservice


cloud:
  config:
    uri: https://github.com/Ramadan877/config-repo

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

