server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

